export const ROUTES = {
  auth: '/(auth)',
  app: '/(app)',
  login: '/(auth)/login',
  register: '/(auth)/register',
  forgotPassword: '/(auth)/forgot-password',
  resetPassword: '/(auth)/reset-password',
  children: '/children',
  linking: '/linking',
  rules: '/rules',
  activity: '/activity',
  settings: '/settings',
  profile: '/profile',
  notifications: '/notifications',
} as const;