export const ROUTES = {
  auth: '/(auth)',
  app: '/(app)',
  onboarding: '/(auth)/onboarding',
  login: '/(auth)/login',
  register: '/(auth)/register',
  forgotPassword: '/(auth)/forgot-password',
  resetPassword: '/(auth)/reset-password',
  children: '/children',
  linking: '/linking',
  rules: '/rules',
  activity: '/activity',
  profile: '/profile',
  profileNotifications: '/profile/notifications',
} as const;